name: PR Deployment

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/your-app:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/your-app:${{ github.sha }}

    - name: Deploy application
      run: |
        ssh user@your_server 'docker-compose up -d --build'

  cleanup:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest

    steps:
    - name: SSH to server and clean up
      run: |
        ssh user@your_server 'docker-compose down'
